version: '3.2'


services:

  nginx:
    container_name: le_shop_nginx
    image: nginx:latest
    ports:
      - ${DOCKER_NGINX_PORT:-20080}:80
    volumes:
      - .:/var/www/le_shop
      - ./docker/nginx/le_shop.conf:/etc/nginx/conf.d/le_shop.conf
    depends_on:
      - php

  php:
#    image: php:8.1-fpm
    container_name: le_shop_php
    ports:
      - ${DOCKER_PHP_PORT:-19000}:9000
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/le_shop
    working_dir: /var/www/le_shop
    depends_on:
      - pgsql

  node:
    container_name: le_shop_node
#    command: bash -c "npm install; npm update && npm run build"
    command: bash -c "npm run dev"
    ports:
      - ${DOCKER_NPM_PORT:-23000}:3000
    image: node:18
    volumes:
      - ./le_view:/var/www/le_shop/le_view
    working_dir: /var/www/le_shop/le_view


  pgsql:
    container_name: le_shop_pgsql
    image: postgres:13.12
    ports:
      - ${DOCKER_PGSQL_PORT:-15432}:5432
    environment:
      - POSTGRES_DB=${LE_SHOP_DOCKER_DB_DB}
      - POSTGRES_USER=${LE_SHOP_DOCKER_DB_USER}
      - POSTGRES_PASSWORD=${LE_SHOP_DOCKER_DB_PASSWORD}
      - TZ=GMT+2
      - PGTZ=GMT+2
    volumes:
      - le_shop_pg_data:/var/lib/postgresql/data:rw
#      - ./docker/postgres/entrypoint/:/docker-entrypoint-initdb.d/ - можемо кидати потрібні ініціалізуючі скрипти

volumes:
  le_shop_pg_data:
    external:
      name: le_shop_pg_data