<?php

namespace common\models;

use yii\db\ActiveRecord;

/**
 * @property int $id
 * @property int $chat_id
 * @property int $user_id
 * @property int $file_size
 * @property string $text
 * @property string $file_id
 *
 */
class TelegramVoiceMessage extends ActiveRecord
{
    public static function tableName()
    {
        return "telegram_voices"; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['text', 'file_id'], 'string'],
            [['chat_id', 'user_id', 'file_size'], 'integer']
        ];
    }
}